# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'RNBaseProj' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'RNBaseProjTests' do
    inherit! :complete
    # Pods for testing
  end

  # post_install do |installer|
  #   # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
  #   react_native_post_install(
  #     installer,
  #     config[:reactNativePath],
  #     :mac_catalyst_enabled => false,
  #     # :ccache_enabled => true
  #   )

  #   installer.pods_project.targets.each do |target|
  #     target.build_configurations.each do |config|
  #       config.build_settings['OTHER_CPLUSPLUSFLAGS'] = [
  #       '$(inherited)',
  #       '-Wno-error=implicit-instantiation-of-undefined-template'
  #     ]
  #     end
  #   end
  # end
  post_install do |installer|
    # Keep the standard React Native post-install steps
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
    )

    # Custom fixes for macOS 15 / New Architecture compilation
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        # 1. Use += to append the flag so you don't lose existing flags
        config.build_settings['OTHER_CPLUSPLUSFLAGS'] ||= ['$(inherited)']
        config.build_settings['OTHER_CPLUSPLUSFLAGS'] << '-Wno-error=implicit-instantiation-of-undefined-template'
        
        # 2. Force turn off "Warnings as Errors"
        # This is critical because Yoga/React Common often have -Werror set
        config.build_settings['GCC_TREAT_WARNINGS_AS_ERRORS'] = 'NO'
        
        # 3. Ensure the C++ standard is high enough for macOS 15
        config.build_settings['CLANG_CXX_LANGUAGE_STANDARD'] = 'c++20'
      end
    end
  end
end
